--
-- ESQUEMA SEGURIDAD
-- Target DBMS : PostgreSQL
--

--
-- TABLE: SEG_BITACORAS_SESSIONES
--

CREATE TABLE SEG_BITACORAS_SESSIONES(
    CVE_BITACORA_SESSION    NUMERIC(11, 0)    NOT NULL,
    SEG_USUARIO             VARCHAR(60),
    FECHA_ENTRADA           DATE,

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_BIT_SESS_C_ID_PK PRIMARY KEY (CVE_BITACORA_SESSION)
)
;



--
-- TABLE: SEG_CATEGORIAS_MODULOS
--

CREATE TABLE SEG_CATEGORIAS_MODULOS(
    CVE_CATEGORIA_MODULO     NUMERIC(11, 0)    NOT NULL,
    DESC_CATEGORIA_MODULO    VARCHAR(25),

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_CAT_MODULOS_ID_PK PRIMARY KEY (CVE_CATEGORIA_MODULO)
)
;



--
-- TABLE: SEG_MODULOS
--

CREATE TABLE SEG_MODULOS(
    CVE_MODULO              NUMERIC(11, 0)    NOT NULL,
    CVE_MODULO_PADRE        NUMERIC(11, 0),
    CVE_CATEGORIA_MODULO    NUMERIC(11, 0)    NOT NULL,
    CODIGO_MODULO           VARCHAR(25),
    DESC_CORTA_MODULO       VARCHAR(40),
    DESC_LARGA_MODULO       VARCHAR(200),
    URL_MODULO              VARCHAR(500),
    ORDEN                   NUMERIC(10, 0),

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_MODULOS_ID_PK PRIMARY KEY (CVE_MODULO)
)
;



--
-- TABLE: SEG_PERFILES
--

CREATE TABLE SEG_PERFILES(
    CVE_PERFIL           NUMERIC(11, 0)    NOT NULL,
    CODIGO_PERFIL        VARCHAR(50),
    DESC_CORTA_PERFIL    VARCHAR(60),
    DESC_LARGA_PERFIL    VARCHAR(150),
    BLOQUEADO            VARCHAR(1)        DEFAULT 'N',
    USUARIO_BLOQUEO      VARCHAR(60),
    FECHA_BLOQUEO        DATE,

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_PERFIL_ID_PK PRIMARY KEY (CVE_PERFIL)
)
;



--
-- TABLE: SEG_PERFILES_MODULOS
--

CREATE TABLE SEG_PERFILES_MODULOS(
    CVE_PERFIL_MODULO    NUMERIC(11, 0)    NOT NULL,
    CVE_MODULO           NUMERIC(11, 0)    NOT NULL,
    CVE_PERFIL           NUMERIC(11, 0)    NOT NULL,

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_PERFIL_MOD_ID_PK PRIMARY KEY (CVE_PERFIL_MODULO)
)
;



--
-- TABLE: SEG_RECURSOS
--

CREATE TABLE SEG_RECURSOS(
    CVE_RECURSO           NUMERIC(11, 0)    NOT NULL,
    CODIGO_RECURSO        VARCHAR(60),
    DESC_RECURSO          VARCHAR(90),
    TABLA_RECURSO         VARCHAR(100),
    CAMPO_CVE_TABLA       VARCHAR(100),
    CAMPO_DESC_TABLA      VARCHAR(100),
    REQUIERE_EJERCICIO    VARCHAR(1)        DEFAULT 'N',
    EJERCICIO_RECURSO     NUMERIC(4, 0),

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_RECURSOS_ID_PK PRIMARY KEY (CVE_RECURSO)
)
;



--
-- TABLE: SEG_RECURSOS_USUARIOS
--

CREATE TABLE SEG_RECURSOS_USUARIOS(
    CVE_RECURSO_USUARIO    NUMERIC(11, 0)    NOT NULL,
    CVE_RECURSO            NUMERIC(11, 0)    NOT NULL,
    SEG_USUARIO            VARCHAR(50)       NOT NULL,
    CAMPO_CVE_TABLA        NUMERIC(11, 0),

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_REC_USUARIO_ID_PK PRIMARY KEY (CVE_RECURSO_USUARIO)
)
;



--
-- TABLE: SEG_USUARIOS
--

CREATE TABLE SEG_USUARIOS(
    SEG_USUARIO              VARCHAR(50)       NOT NULL,
    CONTRASENIA              VARCHAR(80),
    CVE_USUARIO_CATEGORIA    NUMERIC(11, 0)    NOT NULL,
    CVE_MUNICIPIO            NUMERIC(11, 0)    NOT NULL,
    CVE_ESCALON_SANITARIO    NUMERIC(11, 0)    NOT NULL,
    NOMBRE                   VARCHAR(60),
    APELLIDO_PATERNO         VARCHAR(60),
    APELLIDO_MATERNO         VARCHAR(60),
    FECHA_NACIMIENTO         DATE,
    DIRECCION                VARCHAR(200),
    RFC                      VARCHAR(16),
    NUMERO_OFICINA           NUMERIC(18, 0),
    NUMERO_PERSONAL          NUMERIC(18, 0),
    CORREO_ELECTRONICO       VARCHAR(120),
    FECHA_ALTA               DATE,
    FECHA_BLOQUEO            DATE,
    USUARIO_BLOQUEO          VARCHAR(60),
    BLOQUEADO                VARCHAR(10)       DEFAULT 'N',
    SEXO                     CHAR(1),

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_USUARIOS_ID_PK PRIMARY KEY (SEG_USUARIO)
)
;



--
-- TABLE: SEG_USUARIOS_CATEGORIAS
--

CREATE TABLE SEG_USUARIOS_CATEGORIAS(
    CVE_USUARIO_CATEGORIA    NUMERIC(11, 0)    NOT NULL,
    DESC_CATEGORIA           VARCHAR(250),

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_USUARIO_CAT_ID_PK PRIMARY KEY (CVE_USUARIO_CATEGORIA)
)
;



--
-- TABLE: SEG_USUARIOS_PERFILES
--

CREATE TABLE SEG_USUARIOS_PERFILES(
    CVE_USUARIO_PERFIL       NUMERIC(11, 0)    NOT NULL,
    CVE_PERFIL               NUMERIC(11, 0)    NOT NULL,
    SEG_USUARIO              VARCHAR(50)       NOT NULL,
    FECHA_INICIO_VIGENCIA    TIMESTAMP         NOT NULL,
    FECHA_FIN_VIGENCIA       TIMESTAMP,

    FECHA_REGISTRO             TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP  NOT NULL,
    CREADO_POR                 VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_REGISTRO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    FECHA_MODIFICACION         TIMESTAMP WITHOUT TIME ZONE DEFAULT LOCALTIMESTAMP,
    MODIFICADO_POR             VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    IP_MODIFICO                VARCHAR(50) DEFAULT INET_CLIENT_ADDR() NOT NULL,
    ESTATUS_REGISTRO           VARCHAR(3) DEFAULT 'VIG'  NOT null,
    CONSTRAINT S_USUARIO_PERF_ID_PK PRIMARY KEY (CVE_USUARIO_PERFIL)
)
;
